# Generated by Django 6.0 on 2025-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('ma_khoa', models.AutoField(primary_key=True, serialize=False)),
                ('ten_khoa', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('ma_sv', models.AutoField(primary_key=True, serialize=False)),
                ('ten_sv', models.CharField(max_length=500)),
                ('gioi_tinh', models.BooleanField()),
                ('ngay_sinh', models.DateField()),
                ('khoa', models.CharField(max_length=500)),
                ('image_name', models.CharField(max_length=500)),
            ],
        ),
    ]
